services:
  web:
    build: .
    image: pablominue/emotions-diary:latest
    platform: linux/amd64
    command: bash -c "ls -la && gunicorn --bind 0.0.0.0:8000 emotions_diary.wsgi:application && gunicorn logs"
    volumes:
      - .:/app
    ports:
      - "7779:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://emotions_diary:emotions_diary@db/emotions_diary
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - DJANGO_SECRET_KEY="-"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=emotions_diary
      - POSTGRES_USER=emotions_diary
      - POSTGRES_PASSWORD=emotions_diary
volumes:
  postgres_data: