version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://emotions_diary:emotions_diary@db/emotions_diary

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=emotions_diary
      - POSTGRES_USER=emotions_diary
      - POSTGRES_PASSWORD=emotions_diary

volumes:
  postgres_data: