# Generated by Django 5.1.3 on 2024-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotion',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='emotion',
            name='intensity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
    ]
